import type { Destination, Hotel, Activity, Food, Review, FAQ, GalleryImage } from "@/types";

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Kota Beach",
    slug: "kota-beach",
    category: "beach",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "The most popular beach on Bantayan Island with powdery white sand and crystal-clear turquoise waters.",
    fullDescription: "Kota Beach is the crown jewel of Bantayan Island and the first beach most visitors encounter when arriving at Santa Fe. Stretching over a kilometer of pristine white sand, it offers calm, shallow waters ideal for swimming and wading. The beach faces the Visayan Sea and rewards early risers with spectacular sunrises that paint the sky in hues of gold and amber. During peak season, the shoreline comes alive with beach umbrellas, volleyball nets, and the cheerful sounds of vacationers. Several beachfront resorts and restaurants line the shore, offering everything from fresh seafood to refreshing coconut drinks.",
    location: "Santa Fe, Bantayan Island, Cebu",
    openingHours: "Open 24 hours",
    entranceFee: "Free (resort day use available from PHP 150-500)",
    bestTimeToVisit: "December to May, ideal at sunrise and late afternoon",
    tips: [
      "Arrive early to secure a good spot during peak season",
      "Bring reef-safe sunscreen to protect the marine ecosystem",
      "Rent a beach umbrella and chair from nearby vendors",
      "Try the fresh grilled seafood at the beachfront stalls",
      "Watch the stunning sunset from the northern end of the beach"
    ],
    coordinates: { lat: 11.1667, lng: 123.7333 },
    rating: 4.8,
    featured: true,
  },
  {
    id: "2",
    name: "Sugar Beach",
    slug: "sugar-beach",
    category: "beach",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    description: "A secluded stretch of beach with fine white sand like powdered sugar, offering tranquility away from the crowds.",
    fullDescription: "Sugar Beach earns its name from its impossibly fine, white sand that resembles granulated sugar under the tropical sun. Located a short tricycle ride from Bantayan town proper, this beach offers a more peaceful alternative to the busier shorelines. The shallow, warm waters are perfect for children and beginner swimmers, and the gentle waves create a meditative soundtrack for relaxation. Small coconut trees provide natural shade, and local vendors occasionally pass by selling fresh fruits and cold drinks. It is a favorite spot for photographers seeking that perfect, unspoiled beach shot.",
    location: "Bantayan Town, Bantayan Island, Cebu",
    openingHours: "Open 24 hours",
    entranceFee: "Free",
    bestTimeToVisit: "March to May for calmest waters; early morning for solitude",
    tips: [
      "Best visited on weekdays for a more private experience",
      "Bring your own food and water as facilities are limited",
      "Perfect spot for sunrise photography",
      "The shallow waters are great for children",
      "Hire a tricycle for about PHP 100-150 from the town center"
    ],
    coordinates: { lat: 11.1711, lng: 123.7198 },
    rating: 4.6,
    featured: true,
  },
  {
    id: "3",
    name: "Paradise Beach",
    slug: "paradise-beach",
    category: "beach",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "A hidden gem with untouched natural beauty, vivid blue waters, and lush coconut trees framing the shore.",
    fullDescription: "True to its name, Paradise Beach is a slice of heaven that rewards adventurous travelers willing to venture off the beaten path. The beach is accessible via a scenic tricycle and boat ride, adding to its secluded charm. Towering coconut palms lean gracefully over the shoreline, their reflections shimmering in the mirror-like water. The reef just offshore is home to a rich variety of marine life, making it an excellent snorkeling spot. The beach sees fewer tourists than Kota Beach, preserving its natural serenity. Camping is permitted here, and spending a night under the stars with the sound of gentle waves is an unforgettable experience.",
    location: "Northern Bantayan Island, Cebu",
    openingHours: "Open 24 hours",
    entranceFee: "PHP 30 environmental fee",
    bestTimeToVisit: "November to April; early morning for calm seas",
    tips: [
      "Bring snorkeling gear to explore the reef",
      "Camping is allowed — bring your own tent and supplies",
      "Limited food stalls on site; pack your own meals",
      "The boat transfer from shore adds to the adventure",
      "Great spot for stargazing on clear nights"
    ],
    coordinates: { lat: 11.1944, lng: 123.7056 },
    rating: 4.7,
    featured: true,
  },
  {
    id: "4",
    name: "Ogtong Cave Resort",
    slug: "ogtong-cave-resort",
    category: "nature",
    image: "https://images.unsplash.com/photo-1504870712357-65ea720d6078?w=800&q=80",
    description: "A natural cave with a refreshing freshwater spring pool, a unique attraction blending adventure and relaxation.",
    fullDescription: "Ogtong Cave Resort is one of Bantayan Island's most unique attractions, featuring a natural limestone cave with a crystal-clear freshwater spring pool at its heart. The cave is part of a private resort, but day visitors are welcome for a fee. Stalactites hang from the cave ceiling, and filtered sunlight creates an ethereal atmosphere within the grotto. The cold, freshwater pool is a welcome relief from the tropical heat, and its natural mineral content is said to have therapeutic properties. The resort surrounding the cave includes beach access, a restaurant, and accommodation facilities, making it a well-rounded destination.",
    location: "Santa Fe, Bantayan Island, Cebu",
    openingHours: "8:00 AM - 5:00 PM daily",
    entranceFee: "PHP 100 day use (consumable); PHP 200-300 for non-consumable",
    bestTimeToVisit: "Any time; cooler in the morning",
    tips: [
      "Wear water shoes as the cave floor can be slippery",
      "Non-swimmers should use a life jacket available at the resort",
      "Bring a waterproof bag for your valuables",
      "The surrounding resort has a good restaurant for lunch",
      "Photography inside the cave is highly recommended"
    ],
    coordinates: { lat: 11.1648, lng: 123.7221 },
    rating: 4.4,
    featured: true,
  },
  {
    id: "5",
    name: "Virgin Island",
    slug: "virgin-island",
    category: "island",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    description: "A pristine uninhabited sandbar island with emerald waters, perfect for island hopping and snorkeling.",
    fullDescription: "Virgin Island is a breathtaking uninhabited sandbar located a 15-minute boat ride from Bantayan Island's coast. At low tide, a long white sandbar emerges from the sea, creating one of the most photogenic scenes in the entire Visayas region. The surrounding waters are incredibly clear, revealing a colorful coral reef below the surface that teems with sea turtles, colorful fish, and other marine life. Island hopping tours from Santa Fe regularly include Virgin Island, and many operators offer snorkeling equipment rental. The island has no permanent structures, preserving its raw, natural state. Visitors are reminded to take their trash with them and avoid touching or stepping on the coral.",
    location: "Off the coast of Bantayan Island, Cebu",
    openingHours: "Accessible during daylight hours only",
    entranceFee: "PHP 50 environmental fee; boat hire PHP 600-800 per trip",
    bestTimeToVisit: "October to May; low tide for maximum sandbar exposure",
    tips: [
      "Go during low tide to experience the full sandbar",
      "Book a boat tour from Santa Fe Port for PHP 600-800",
      "Bring your own snorkeling gear or rent from the tour operator",
      "There are no facilities — bring food, water, and sunscreen",
      "Sea turtles are commonly spotted here — do not disturb them"
    ],
    coordinates: { lat: 11.1398, lng: 123.7556 },
    rating: 4.9,
    featured: true,
  },
  {
    id: "6",
    name: "Sandira Beach",
    slug: "sandira-beach",
    category: "beach",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    description: "A quiet, family-friendly beach known for its calm shallow waters and breathtaking panoramic views.",
    fullDescription: "Sandira Beach is a peaceful stretch of coastline that has gained popularity among families and couples seeking a quieter beach experience. The waters here are remarkably calm due to a natural reef barrier, creating a large, shallow lagoon that is safe for children and non-swimmers. Local fishermen bring their colorful outrigger boats ashore here, adding authentic character to the scene. The beach is less developed than Kota Beach, which means fewer crowds and a more genuine local atmosphere. Several small eateries nearby serve fresh catch of the day, and the community fishing village adjacent to the beach offers interesting cultural insights.",
    location: "Bantayan Town, Bantayan Island, Cebu",
    openingHours: "Open 24 hours",
    entranceFee: "Free",
    bestTimeToVisit: "Year-round; December to May for best weather",
    tips: [
      "Ideal for families with young children due to shallow water",
      "Observe local fishermen preparing their nets in the morning",
      "Affordable seafood can be bought directly from the fishermen",
      "Bring shade as trees are sparse along the beach",
      "Combine with a visit to the nearby town center"
    ],
    coordinates: { lat: 11.1733, lng: 123.7267 },
    rating: 4.3,
    featured: false,
  },
  {
    id: "7",
    name: "Baigad Lagoon",
    slug: "baigad-lagoon",
    category: "nature",
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80",
    description: "A tranquil natural lagoon surrounded by mangroves and wildlife, perfect for kayaking and bird watching.",
    fullDescription: "Baigad Lagoon is a serene natural wonder tucked away from Bantayan's main tourist circuit. The calm, brackish lagoon is enclosed by a dense mangrove forest, creating a rich ecosystem that supports numerous bird species, fish, and other wildlife. Kayaking through the narrow mangrove channels is one of the most peaceful activities on the island, offering an intimate connection with nature. Bird watchers will delight in spotting migratory and endemic species, particularly at dawn and dusk. The lagoon is also an important nursery for fish and shellfish, underscoring its ecological significance. Local guides can arrange kayaking tours that include wildlife spotting and mangrove education.",
    location: "Baigad, Bantayan Island, Cebu",
    openingHours: "6:00 AM - 6:00 PM daily",
    entranceFee: "PHP 50; kayak rental PHP 200 per hour",
    bestTimeToVisit: "Early morning or late afternoon for wildlife activity",
    tips: [
      "Hire a local guide for a richer, more informative experience",
      "Bring binoculars for bird watching",
      "Wear light, quick-dry clothing",
      "Early morning visits offer the calmest water and most wildlife",
      "Respect the ecosystem — no littering or disturbing animals"
    ],
    coordinates: { lat: 11.1856, lng: 123.6956 },
    rating: 4.5,
    featured: false,
  },
  {
    id: "8",
    name: "Mangrove Eco Park",
    slug: "mangrove-eco-park",
    category: "nature",
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80",
    description: "An eco-tourism site with elevated walkways through dense mangrove forests, promoting conservation and education.",
    fullDescription: "The Bantayan Mangrove Eco Park is a community-managed ecological attraction that offers visitors an educational and immersive walk through one of the Philippines' well-preserved mangrove forests. Elevated bamboo walkways snake through the dense canopy, allowing visitors to explore the ecosystem without disturbing the forest floor. Informative signs along the trail explain the critical role mangroves play in coastal protection, carbon sequestration, and as nurseries for marine life. The park is part of a broader conservation effort by the local community, and entrance fees directly support maintenance and replanting programs. It is an excellent destination for eco-conscious travelers and families seeking educational experiences.",
    location: "Bantayan Island, Cebu",
    openingHours: "7:00 AM - 5:00 PM daily",
    entranceFee: "PHP 30 per person",
    bestTimeToVisit: "Morning or late afternoon to avoid midday heat",
    tips: [
      "Wear comfortable walking shoes",
      "Bring insect repellent — mosquitoes can be present",
      "Photography is excellent in the early morning light",
      "Children will love the elevated walkway experience",
      "Support conservation by following all park guidelines"
    ],
    coordinates: { lat: 11.1667, lng: 123.7000 },
    rating: 4.4,
    featured: false,
  },
  {
    id: "9",
    name: "Bantayan Public Plaza",
    slug: "bantayan-public-plaza",
    category: "attraction",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
    description: "The historical heart of Bantayan town featuring a well-maintained park, colonial-era structures, and vibrant local life.",
    fullDescription: "Bantayan Public Plaza serves as the social and cultural center of Bantayan town, a space where history, community, and everyday life converge. The plaza is flanked by well-preserved Spanish colonial buildings, including the town hall and old municipal structures that speak to the island's centuries-old heritage. Well-manicured gardens, benches, and a central gazebo make it a beloved gathering place for locals of all ages. On weekends and holidays, the plaza comes alive with impromptu events, food vendors selling local delicacies, and children playing. It is an excellent starting point for exploring the historic town of Bantayan and getting a genuine sense of island culture and daily life.",
    location: "Bantayan Town, Bantayan Island, Cebu",
    openingHours: "Open 24 hours",
    entranceFee: "Free",
    bestTimeToVisit: "Early evening when locals gather; weekends for community events",
    tips: [
      "Visit in the evening when the plaza is most lively",
      "Walk to the nearby church, which is just steps away",
      "Try local snacks from the food stalls around the plaza",
      "Great spot to interact with friendly locals",
      "Weekend mornings feature a small local market"
    ],
    coordinates: { lat: 11.1667, lng: 123.7167 },
    rating: 4.2,
    featured: false,
  },
  {
    id: "10",
    name: "Sts. Peter and Paul Parish Church",
    slug: "sts-peter-paul-parish-church",
    category: "church",
    image: "https://images.unsplash.com/photo-1548625149-720754953e6e?w=800&q=80",
    description: "One of the oldest churches in Cebu, a stunning 17th-century coral stone structure of immense historical and spiritual significance.",
    fullDescription: "The Parish Church of Sts. Peter and Paul in Bantayan Town is one of the oldest and most beautifully preserved churches in the Visayas region. Constructed in the early 1600s by Spanish Augustinian friars, the church is built from coral stones harvested from the surrounding seas, giving it a distinctive pale, weathered facade that has stood the test of centuries. The church played a pivotal role in the Christianization of the Visayan people, and its thick walls and fortified design also served as a refuge during pirate raids. Inside, the retablo and religious artworks reflect the fusion of Spanish Baroque and Filipino craftsmanship. The church remains an active place of worship and is a deeply revered landmark for the local community.",
    location: "Bantayan Town, Bantayan Island, Cebu",
    openingHours: "6:00 AM - 7:00 PM daily; closed during Mass times for tourists",
    entranceFee: "Free (donations welcome)",
    bestTimeToVisit: "Early morning or late afternoon for best lighting; avoid Sundays during Mass",
    tips: [
      "Dress modestly — cover shoulders and knees",
      "Photography is allowed outside; ask permission inside",
      "Visit during the Ati-atihan festival in January for a spectacular experience",
      "The church grounds offer excellent architectural photography",
      "A tour guide can provide fascinating historical context"
    ],
    coordinates: { lat: 11.1656, lng: 123.7178 },
    rating: 4.7,
    featured: true,
  },
  {
    id: "11",
    name: "Omagieca Mangrove Garden",
    slug: "omagieca-mangrove-garden",
    category: "nature",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    description: "A hidden garden sanctuary with a picturesque bamboo bridge over mangroves, ideal for photography and peaceful reflection.",
    fullDescription: "The Omagieca Mangrove Garden is a hidden gem that has captured the hearts of travelers and photographers alike. Named after the barangay it calls home, this community-developed eco-park features a scenic bamboo footbridge that winds over a serene mangrove lagoon, creating one of the most photogenic spots on Bantayan Island. The reflections of mangroves in the still water below the bridge are particularly stunning in the golden hour light. The garden is maintained by local residents who take immense pride in its upkeep, and visiting supports the community directly. The setting is tranquil and meditative, making it perfect for those who want a break from the beach.",
    location: "Omagieca, Bantayan Island, Cebu",
    openingHours: "7:00 AM - 5:00 PM daily",
    entranceFee: "PHP 30 per person",
    bestTimeToVisit: "Golden hour (sunrise or sunset) for the best photography",
    tips: [
      "Visit at sunrise for mirror-like reflections and soft light",
      "Bring a wide-angle lens for landscape photography",
      "The bamboo bridge makes for exceptional Instagram-worthy shots",
      "Wear shoes that can get slightly muddy",
      "A local guide can enhance your visit with stories about the area"
    ],
    coordinates: { lat: 11.1756, lng: 123.6878 },
    rating: 4.5,
    featured: false,
  },
  {
    id: "12",
    name: "Camp Sawi",
    slug: "camp-sawi",
    category: "attraction",
    image: "https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800&q=80",
    description: "A unique nature camp that gained fame as the filming location of the hit Filipino film, surrounded by serene nature.",
    fullDescription: "Camp Sawi gained significant attention after serving as the filming location for the popular Filipino romantic comedy film 'Camp Sawi.' Since then, it has transformed from a quiet nature camp into a bustling tourist destination that blends natural beauty with pop culture significance. The camp is nestled between towering coconut palms and fronts a peaceful stretch of beach, creating a rustic, tropical paradise atmosphere. Visitors can rent camping tents, hammocks, and native huts while enjoying bonfires on the beach at night. The camp's authenticity and connection to Filipino cinema give it a charm that resonates with both nature lovers and film enthusiasts.",
    location: "Kaongkod, Bantayan Island, Cebu",
    openingHours: "Open 24 hours (camping facilities)",
    entranceFee: "PHP 50 day use; camping packages from PHP 500",
    bestTimeToVisit: "November to April for best weather; weekdays for fewer crowds",
    tips: [
      "Book camping accommodations in advance during peak season",
      "The bonfire on the beach at night is a magical experience",
      "Bring your own food or purchase from the camp's small kitchen",
      "The site is about 8 km from Santa Fe — rent a scooter or hire a tricycle",
      "Fans of the film will recognize many iconic spots on site"
    ],
    coordinates: { lat: 11.2000, lng: 123.7444 },
    rating: 4.3,
    featured: false,
  },
  {
    id: "13",
    name: "Hilantagaan Island",
    slug: "hilantagaan-island",
    category: "island",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    description: "A remote island paradise with pristine reefs, exceptional diving, and an untouched natural environment.",
    fullDescription: "Hilantagaan Island is one of the most remote and rewarding destinations accessible from Bantayan Island. Located about an hour's boat ride away, this small island is celebrated for its exceptional underwater biodiversity. The coral gardens surrounding the island are among the most pristine in the Visayas, attracting experienced divers and snorkelers from around the world. Above water, the island's small fishing community lives in harmony with the sea, and visitors can witness traditional fishing practices firsthand. The beach is narrow but beautiful, and the turquoise waters are so clear you can see the bottom at depths of several meters. It is a destination for those who truly want to escape civilization.",
    location: "Off the northern coast of Bantayan Island",
    openingHours: "Accessible during daylight hours only",
    entranceFee: "PHP 50 environmental fee; boat hire from PHP 1,000-1,500 round trip",
    bestTimeToVisit: "March to May for calm seas and best visibility",
    tips: [
      "Hire a boat with a local guide who knows the reef layout",
      "Bring all supplies — no shops on the island",
      "Bring professional diving equipment or arrange rentals in advance",
      "Respect the local fishing community and their way of life",
      "Pack reef-safe sunscreen to protect the pristine coral"
    ],
    coordinates: { lat: 11.2333, lng: 123.7500 },
    rating: 4.8,
    featured: false,
  },
  {
    id: "14",
    name: "Silion Island",
    slug: "silion-island",
    category: "island",
    image: "https://images.unsplash.com/photo-1490394813925-88e0b9f10e4e?w=800&q=80",
    description: "A small, idyllic island with crystal waters and a peaceful atmosphere perfect for a private island escape.",
    fullDescription: "Silion Island is a small, exquisite gem in the cluster of islands surrounding Bantayan. While less visited than Virgin Island, Silion offers a comparably stunning natural environment with the added benefit of being quieter and more intimate. The island is ringed by a shallow reef that creates a natural swimming pool of warm, crystal-clear water. At low tide, you can wade between the island and nearby sandbars. The fishing village on the island is a window into traditional Cebuano coastal life, and the residents are known for their warmth and hospitality. A few basic homestays have emerged to accommodate overnight visitors who want a truly off-grid experience.",
    location: "West of Bantayan Island, Cebu",
    openingHours: "Accessible during daylight hours only",
    entranceFee: "PHP 30 environmental fee; boat hire PHP 800-1,200",
    bestTimeToVisit: "November to May for calm sea conditions",
    tips: [
      "Go during low tide to walk the exposed sandbars",
      "A homestay with a local family offers authentic island living",
      "Bring cash as there are no ATMs on the island",
      "The snorkeling around the island is excellent",
      "Combine with a visit to nearby Virgin Island"
    ],
    coordinates: { lat: 11.1500, lng: 123.7000 },
    rating: 4.6,
    featured: false,
  },
  {
    id: "15",
    name: "Santa Fe Port",
    slug: "santa-fe-port",
    category: "attraction",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "The main gateway to Bantayan Island and a vibrant hub of maritime activity, seafood, and local culture.",
    fullDescription: "Santa Fe Port is far more than just a transit point — it is the living, breathing heart of Bantayan Island's maritime culture. The port buzzes with activity throughout the day as ferries from Hagnaya arrive bringing visitors, supplies, and mainland Cebu's influence. The port area is lined with stalls selling fresh seafood, dried fish, and local produce, making it a sensory feast from the moment you step off the ferry. Fishing boats dock alongside passenger ferries, and the sight of fishermen unloading the morning's catch is a quintessential Bantayan experience. The port's surroundings have several affordable restaurants and shops, and it serves as the main hub for hiring tricycles, scooters, and booking island hopping tours.",
    location: "Santa Fe, Bantayan Island, Cebu",
    openingHours: "4:00 AM - 9:00 PM (ferry schedule dependent)",
    entranceFee: "Free",
    bestTimeToVisit: "Morning when the catch is freshest and the atmosphere is most vibrant",
    tips: [
      "The ferry from Hagnaya costs approximately PHP 175-200 per person",
      "Arrange transportation from the port to your accommodation in advance",
      "Buy dried seafood souvenirs from the port stalls at good prices",
      "Check the ferry schedule before planning your departure day",
      "The area around the port has good, affordable seafood restaurants"
    ],
    coordinates: { lat: 11.1569, lng: 123.7900 },
    rating: 4.3,
    featured: false,
  },
];

export const hotels: Hotel[] = [
  {
    id: "1",
    name: "Kota Beach Resort",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    priceRange: "PHP 2,500 - 6,000 / night",
    rating: 4.6,
    reviewCount: 1243,
    amenities: ["Beachfront", "Pool", "Restaurant", "Free WiFi", "Air Conditioning", "Water Sports"],
    description: "The premier beachfront resort on Bantayan Island, Kota Beach Resort sits directly on the island's most famous stretch of white sand. The resort features elegantly designed native-inspired cottages and modern rooms, all with ocean views. Guests enjoy direct beach access, a large infinity pool, and an open-air restaurant serving fresh seafood and Filipino favorites.",
    location: "Santa Fe, Bantayan Island",
    featured: true,
  },
  {
    id: "2",
    name: "Anika Island Resort",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    priceRange: "PHP 3,000 - 8,000 / night",
    rating: 4.7,
    reviewCount: 876,
    amenities: ["Private Beach", "Infinity Pool", "Spa", "Restaurant", "Bar", "Free WiFi", "Kayaking"],
    description: "Anika Island Resort offers an upscale island retreat combining modern luxury with the natural beauty of Bantayan. The resort's signature infinity pool appears to merge with the ocean horizon, creating one of the most memorable views on the island. Premium cottages are crafted from local materials with contemporary interiors, and the spa offers traditional Filipino healing treatments.",
    location: "Santa Fe, Bantayan Island",
    featured: true,
  },
  {
    id: "3",
    name: "Hoyohoy Villas",
    image: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80",
    priceRange: "PHP 1,800 - 4,500 / night",
    rating: 4.4,
    reviewCount: 654,
    amenities: ["Garden", "Pool", "Restaurant", "Free WiFi", "Air Conditioning", "Bicycle Rental"],
    description: "Hoyohoy Villas is a charming boutique property that perfectly captures the laid-back spirit of Bantayan Island living. Set amidst tropical gardens just a short walk from the beach, the villas are individually designed native-style units that offer both privacy and comfort. The communal pool area is surrounded by lush greenery, and the in-house restaurant serves excellent breakfasts using locally sourced ingredients.",
    location: "Santa Fe, Bantayan Island",
    featured: false,
  },
  {
    id: "4",
    name: "Amihan Beach Cabanas",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    priceRange: "PHP 2,000 - 5,500 / night",
    rating: 4.5,
    reviewCount: 432,
    amenities: ["Beachfront", "Restaurant", "Bar", "Free WiFi", "Air Conditioning", "Snorkeling Gear"],
    description: "Amihan Beach Cabanas offers an intimate beachfront experience with individually designed native cabanas perched right on the sand. Named after the cool northeast wind that blows across the island during the dry season, the resort embodies relaxed island hospitality. The open-air beach bar is legendary for its sunset cocktails, and the kitchen prepares excellent fresh seafood dishes daily.",
    location: "Santa Fe, Bantayan Island",
    featured: false,
  },
  {
    id: "5",
    name: "Jelly's Haven Resort",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    priceRange: "PHP 1,500 - 3,500 / night",
    rating: 4.3,
    reviewCount: 312,
    amenities: ["Beach Access", "Pool", "Restaurant", "Free WiFi", "Family Rooms", "Tour Desk"],
    description: "Jelly's Haven Resort is a family-friendly property that offers excellent value without sacrificing comfort. The resort is particularly popular with families, offering spacious rooms that accommodate groups, a playground area for children, and a shallow wading pool. The resort's tour desk can arrange all island activities, from island hopping to snorkeling tours, making it a convenient base for exploration.",
    location: "Santa Fe, Bantayan Island",
    featured: false,
  },
  {
    id: "6",
    name: "Sunday Flower Hotel",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    priceRange: "PHP 1,200 - 2,800 / night",
    rating: 4.2,
    reviewCount: 567,
    amenities: ["Near Beach", "Free WiFi", "Air Conditioning", "Breakfast Included", "Parking"],
    description: "Sunday Flower Hotel is a clean, comfortable mid-range option that offers excellent value in Bantayan Town. Just a five-minute walk from the beach, the hotel features well-appointed standard and superior rooms with modern amenities. A complimentary breakfast is included in all room rates, featuring a mix of Filipino and continental options. The friendly staff are knowledgeable about local attractions and happy to assist with tour arrangements.",
    location: "Bantayan Town, Bantayan Island",
    featured: false,
  },
  {
    id: "7",
    name: "La Playa Estrella Beach Resort",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    priceRange: "PHP 2,200 - 5,000 / night",
    rating: 4.5,
    reviewCount: 289,
    amenities: ["Beachfront", "Pool", "Restaurant", "Beach Bar", "Free WiFi", "Hammocks"],
    description: "La Playa Estrella, meaning 'The Beach Star,' lives up to its celestial name with a beachfront setting that glows particularly brilliantly at sunset. The resort features a curated collection of spacious bungalows and superior rooms, all styled with a Mediterranean-meets-tropical aesthetic that is distinctly its own. The beachside hammock area is famous among guests, and the pool bar serves creative cocktails inspired by island ingredients.",
    location: "Santa Fe, Bantayan Island",
    featured: false,
  },
  {
    id: "8",
    name: "Maia's Beach Resort",
    image: "https://images.unsplash.com/photo-1525596662741-e94ff9f26de1?w=800&q=80",
    priceRange: "PHP 1,800 - 4,000 / night",
    rating: 4.4,
    reviewCount: 378,
    amenities: ["Beach Access", "Pool", "Restaurant", "Kayaking", "Free WiFi", "Air Conditioning"],
    description: "Maia's Beach Resort is a hidden gem that consistently earns praise for its personalized service and warm, family-run atmosphere. The resort offers a range of accommodation from fan rooms to air-conditioned cottages, all maintained to a high standard of cleanliness. The open-air restaurant overlooks a beautiful stretch of beach and serves outstanding fresh seafood prepared with local spices and cooking techniques.",
    location: "Santa Fe, Bantayan Island",
    featured: false,
  },
];

export const activities: Activity[] = [
  {
    id: "1",
    name: "Island Hopping",
    icon: "Anchor",
    description: "Explore the surrounding islands including Virgin Island, Hilantagaan, and Silion Island on an exhilarating full-day or half-day boat tour.",
    price: "PHP 600 - 1,500 per boat",
    duration: "4-8 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
  },
  {
    id: "2",
    name: "Snorkeling",
    icon: "Fish",
    description: "Discover vibrant coral reefs and abundant marine life in the crystal-clear waters surrounding Bantayan Island.",
    price: "PHP 200 - 400 (gear rental)",
    duration: "1-3 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80",
  },
  {
    id: "3",
    name: "Scuba Diving",
    icon: "Waves",
    description: "Explore dramatic underwater landscapes with diverse coral gardens, sea turtles, and colorful reef fish around the island's premier dive sites.",
    price: "PHP 1,500 - 3,000 per dive",
    duration: "2-4 hours",
    difficulty: "moderate",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
  },
  {
    id: "4",
    name: "Kayaking",
    icon: "Navigation",
    description: "Paddle through calm waters along the coastline, mangrove channels, and into secluded coves that are unreachable by larger boats.",
    price: "PHP 150 - 300 per hour",
    duration: "1-3 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1504870712357-65ea720d6078?w=800&q=80",
  },
  {
    id: "5",
    name: "Paddleboarding",
    icon: "Move",
    description: "Stand-up paddleboarding along the glassy morning waters is the perfect way to experience the island's beauty from a unique vantage point.",
    price: "PHP 250 - 400 per hour",
    duration: "1-2 hours",
    difficulty: "moderate",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: "6",
    name: "Beach Camping",
    icon: "Tent",
    description: "Sleep under a canopy of stars on Paradise Beach or at Camp Sawi, with bonfires, gentle waves, and the milky way overhead.",
    price: "PHP 300 - 600 per night",
    duration: "Overnight",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800&q=80",
  },
  {
    id: "7",
    name: "Sunset Watching",
    icon: "Sun",
    description: "Bantayan Island's west-facing coast offers some of the most spectacular sunsets in the Philippines, best enjoyed from the beach with a cold drink.",
    price: "Free",
    duration: "1-2 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
  },
  {
    id: "8",
    name: "Bicycle Rental",
    icon: "Bike",
    description: "Explore the island's towns, hidden beaches, and rural landscapes at your own pace on a bicycle, one of the most popular ways to see Bantayan.",
    price: "PHP 100 - 200 per day",
    duration: "Flexible",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
  },
  {
    id: "9",
    name: "Scooter Rental",
    icon: "Gauge",
    description: "Cover more ground on a scooter and discover all three main towns of Bantayan Island along with remote beaches and viewpoints.",
    price: "PHP 400 - 600 per day",
    duration: "Flexible",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
  },
  {
    id: "10",
    name: "Fishing Tours",
    icon: "Fish",
    description: "Join local fishermen on an early morning fishing trip and experience traditional Filipino fishing techniques in the waters of the Visayan Sea.",
    price: "PHP 500 - 1,000 per person",
    duration: "4-6 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
  },
  {
    id: "11",
    name: "Seafood Dining",
    icon: "UtensilsCrossed",
    description: "Indulge in the island's famous fresh seafood — from grilled bangus to kinilaw — at beachfront restaurants and local eateries.",
    price: "PHP 200 - 800 per person",
    duration: "1-2 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
  },
  {
    id: "12",
    name: "Photography Tours",
    icon: "Camera",
    description: "Capture the island's most photogenic spots — from the bamboo bridges at Omagieca to the golden hour light at Virgin Island's sandbar.",
    price: "PHP 500 - 1,200 with guide",
    duration: "3-6 hours",
    difficulty: "easy",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
  },
];

export const foods: Food[] = [
  {
    id: "1",
    name: "Fresh Grilled Seafood",
    description: "The undisputed highlight of any visit to Bantayan Island — fresh catch of the day grilled over charcoal and served with garlic rice, vinegar dipping sauce, and sliced tomatoes. The simplicity of the preparation lets the extraordinary freshness of the seafood speak for itself.",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
    type: "seafood",
    price: "PHP 150 - 400",
    whereTryIt: "Kota Beach beachfront restaurants, Santa Fe Port area",
  },
  {
    id: "2",
    name: "Scallops",
    description: "Bantayan Island is renowned throughout the Philippines for its extraordinary scallops — large, plump, and sweet. Served grilled in the half shell with butter, garlic, and a squeeze of citrus, or baked with cheese, they are an absolute must-try that visitors routinely name as the best scallops of their lives.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    type: "seafood",
    price: "PHP 100 - 250 per order",
    whereTryIt: "Scallop stalls along the Santa Fe market, beachfront restaurants",
  },
  {
    id: "3",
    name: "Kinilaw",
    description: "Bantayan's version of ceviche — fresh raw fish or shellfish cured in coconut vinegar and calamansi juice, then tossed with sliced onions, ginger, red chili, and fresh tomatoes. The acid 'cooking' process creates a refreshing dish with bright, clean flavors that perfectly capture the essence of island cooking.",
    image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3b84?w=800&q=80",
    type: "seafood",
    price: "PHP 120 - 200",
    whereTryIt: "Local restaurants and eateries throughout Bantayan town",
  },
  {
    id: "4",
    name: "Lechon",
    description: "The Philippines' most celebrated dish takes on special significance on Bantayan Island, where roasted whole suckling pig is a centerpiece of every major celebration and gathering. The skin is crackled to a deep mahogany perfection, and the meat inside is tender and richly seasoned with herbs and spices.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    type: "local",
    price: "PHP 200 - 350 per serving",
    whereTryIt: "Bantayan town market, carinderia restaurants",
  },
  {
    id: "5",
    name: "Chicken Inasal",
    description: "Chicken marinated in a fragrant blend of calamansi, achuete (annatto), garlic, ginger, lemongrass, and coconut vinegar, then grilled over hot charcoal until the skin crisps and chars in all the right places. Served with sawsawan (dipping sauce) and garlic rice for a quintessential Visayan meal.",
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80",
    type: "local",
    price: "PHP 80 - 150 per piece",
    whereTryIt: "Inasal stalls throughout Bantayan and Santa Fe",
  },
  {
    id: "6",
    name: "Danggit",
    description: "Bantayan Island's most famous food export — sun-dried rabbitfish that is deep-fried until golden and crispy. The intensely savory, slightly pungent flavor of danggit paired with steamed rice and fresh tomatoes is the classic Cebuano breakfast. Dried danggit is the most popular pasalubong (souvenir) to bring home.",
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
    type: "seafood",
    price: "PHP 50 - 120 per order",
    whereTryIt: "Markets in all towns, port area vendors",
  },
  {
    id: "7",
    name: "Puso Rice",
    description: "A uniquely Cebuano tradition — freshly cooked rice stuffed into hand-woven coconut leaf packets and boiled or steamed. The triangular diamond-shaped puso is a portable, mess-free way to enjoy rice that is a staple at every carinderia and street food stall. Its slightly firm texture and neutral flavor make it the perfect companion for grilled meats and seafood.",
    image: "https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800&q=80",
    type: "local",
    price: "PHP 5 - 10 per piece",
    whereTryIt: "Street food stalls and carinderias throughout the island",
  },
  {
    id: "8",
    name: "Halo-Halo",
    description: "The Philippines' beloved summer dessert is particularly refreshing on Bantayan Island after a long day in the sun. A generous parfait of shaved ice, evaporated milk, and up to a dozen colorful ingredients — sweetened beans, macapuno coconut, nata de coco, leche flan, ube halaya, and a scoop of ice cream on top. Each spoonful is a different flavor combination.",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    type: "dessert",
    price: "PHP 60 - 120",
    whereTryIt: "Merienda shops and restaurants throughout the island",
  },
  {
    id: "9",
    name: "Fresh Coconut Juice",
    description: "Nothing quenches the tropical thirst like a young green coconut, expertly cracked open and served ice-cold with a straw. The water inside is naturally sweet, subtly nutty, and electrolyte-rich — nature's perfect sports drink. After drinking, the vendor will split the coconut open so you can scrape and eat the tender, jelly-like flesh inside.",
    image: "https://images.unsplash.com/photo-1504870712357-65ea720d6078?w=800&q=80",
    type: "drink",
    price: "PHP 20 - 40 per coconut",
    whereTryIt: "Beach vendors, roadside stands throughout the island",
  },
  {
    id: "10",
    name: "Mango Shake",
    description: "Filipino mangoes are widely considered among the finest in the world, and on Bantayan Island, fresh mango shakes made with ripe Carabao mangoes blend silky smooth, intensely sweet, and faintly floral. Blended with crushed ice and a splash of fresh milk, it is the perfect beach companion on a hot afternoon.",
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80",
    type: "drink",
    price: "PHP 40 - 80",
    whereTryIt: "Beachfront cafes and refreshment stalls",
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    country: "United States",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    rating: 5,
    date: "March 2024",
    review: "Bantayan Island completely surpassed every expectation I had. The beaches are absolutely pristine — the sand at Kota Beach is so white and fine it looks like something from a screensaver. We went island hopping to Virgin Island and were left speechless by the clarity of the water and the colors of the reef. The scallops are the best I have eaten anywhere in the world. I cannot recommend this place highly enough.",
    destination: "Kota Beach & Virgin Island",
  },
  {
    id: "2",
    name: "James Whitfield",
    country: "United Kingdom",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    rating: 5,
    date: "January 2024",
    review: "We spent eight days on Bantayan and could have stayed for months. The pace of life here is wonderfully slow and the locals are incredibly friendly and welcoming. Exploring the island by scooter revealed beaches we would never have found otherwise. The Ogtong Cave was a surprising highlight — swimming in a natural freshwater cave with stalactites above you is a surreal and wonderful experience.",
    destination: "Ogtong Cave & Sugar Beach",
  },
  {
    id: "3",
    name: "Ana Reyes",
    country: "Spain",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    rating: 5,
    date: "December 2023",
    review: "Bantayan is everything Boracay used to be before it became overcrowded — natural, authentic, affordable, and breathtakingly beautiful. The Omagieca Mangrove Garden at golden hour gave us some of the most beautiful travel photographs of our trip. The food is exceptional, especially the fresh seafood and the Cebuano danggit for breakfast. We will absolutely be returning.",
    destination: "Omagieca Mangrove Garden",
  },
  {
    id: "4",
    name: "Daniel Hofmann",
    country: "Germany",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    rating: 4,
    date: "February 2024",
    review: "Fantastic island with genuinely world-class beaches. Paradise Beach lived up to its name completely — we had nearly the entire beach to ourselves on a Tuesday morning. The snorkeling at Hilantagaan Island was exceptional and the dive visibility was outstanding. My only small note is that some of the island roads are rough, so rent a quality scooter. Otherwise this is a perfect destination.",
    destination: "Paradise Beach & Hilantagaan Island",
  },
  {
    id: "5",
    name: "Jessica Tanaka",
    country: "Japan",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    rating: 5,
    date: "April 2024",
    review: "I came to Bantayan Island for a weekend and extended my stay twice, staying for nearly two weeks in the end. The sunsets from the western coast are among the most beautiful I have witnessed in years of travel. Renting a bicycle and exploring the island independently was a joy. The historic church in Bantayan town is magnificent and the local food scene far exceeded my expectations.",
    destination: "Bantayan Town & Beaches",
  },
  {
    id: "6",
    name: "Marco Bianchi",
    country: "Italy",
    avatar: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=200&q=80",
    rating: 5,
    date: "May 2024",
    review: "Bantayan Island is the closest thing to paradise I have found in Southeast Asia. The Virgin Island sandbar at low tide is one of the great natural spectacles of the Philippines. We stayed at Anika Island Resort and the infinity pool overlooking the ocean was breathtaking. If you are looking for unspoiled Philippine island beauty without the crowds of the more famous islands, Bantayan is your answer.",
    destination: "Virgin Island & Kota Beach",
  },
];

export const faqs: FAQ[] = [
  {
    id: "1",
    question: "How do I get to Bantayan Island from Cebu City?",
    answer: "Take a bus or van from Cebu's North Bus Terminal to Hagnaya Port in San Remigio (approximately 3-4 hours, PHP 100-130). From Hagnaya Port, take a ferry to Santa Fe Port on Bantayan Island (approximately 1 hour, PHP 175-200 per person). Combined travel time is about 4-5 hours.",
  },
  {
    id: "2",
    question: "What is the best time of year to visit Bantayan Island?",
    answer: "The best time to visit is during the dry season from December to May, with March to May offering the calmest seas and best visibility for water activities. January and February are particularly popular for their comfortable temperatures and low rainfall. The island can still be visited during the rainy season (June to November) but water activities may be limited on some days.",
  },
  {
    id: "3",
    question: "How much does it cost to visit Bantayan Island on a budget?",
    answer: "Bantayan is one of the Philippines' more affordable island destinations. Budget travelers can get by on PHP 800-1,200 per day (excluding accommodation), covering meals at local eateries, transportation, and some activities. Budget accommodation is available from PHP 500-1,500 per night. A comfortable mid-range visit typically runs PHP 2,000-4,000 per day all-in.",
  },
  {
    id: "4",
    question: "Are there ATMs on Bantayan Island?",
    answer: "Yes, there are ATM machines in Bantayan Town and Santa Fe, but they can run out of cash during peak season or have long queues. It is strongly recommended to withdraw enough cash in Cebu City or Hagnaya before making the crossing, as card payment is not widely accepted by local restaurants and smaller shops.",
  },
  {
    id: "5",
    question: "Is Bantayan Island safe for tourists?",
    answer: "Yes, Bantayan Island is generally considered a very safe destination for tourists. The local communities are welcoming and the island has low crime rates. As with any travel destination, standard precautions apply: keep valuables secured, do not leave belongings unattended on the beach, and be cautious when swimming in unfamiliar waters.",
  },
  {
    id: "6",
    question: "Is there reliable internet and mobile signal on the island?",
    answer: "Mobile signal is available throughout the island from major carriers (Globe and Smart), though signal strength varies in more remote areas. Most resorts and restaurants in Santa Fe and Bantayan town offer free WiFi, though speeds can be slow during peak hours. Download offline maps before arriving for backup navigation.",
  },
  {
    id: "7",
    question: "What should I pack for a trip to Bantayan Island?",
    answer: "Pack reef-safe sunscreen, light quick-dry clothing, insect repellent (especially for mangrove areas), comfortable walking shoes, flip-flops, a reusable water bottle, snorkeling gear if you have your own, a waterproof bag for boat trips, sufficient cash in Philippine Pesos, and a power bank. Bring any prescription medications as pharmacies on the island have limited stock.",
  },
  {
    id: "8",
    question: "Can I visit Bantayan Island on a day trip?",
    answer: "Technically possible but not recommended. The travel time from Cebu City (4-5 hours each way) leaves very little time to experience what the island has to offer. At minimum, plan for 2-3 nights to enjoy the beaches, do some island hopping, and try the local food at a relaxed pace. Most visitors find they want to stay longer than planned.",
  },
];

export const galleryImages: GalleryImage[] = [
  { id: "1", src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", alt: "Bantayan Island Beach at Sunset", category: "beaches", width: 1200, height: 800 },
  { id: "2", src: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80", alt: "Snorkeling at Virgin Island", category: "activities", width: 800, height: 1000 },
  { id: "3", src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", alt: "Paradise Beach Crystal Waters", category: "beaches", width: 1200, height: 800 },
  { id: "4", src: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80", alt: "Hilantagaan Island Aerial View", category: "islands", width: 1000, height: 800 },
  { id: "5", src: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80", alt: "Colorful Marine Life Snorkeling", category: "activities", width: 800, height: 1000 },
  { id: "6", src: "https://images.unsplash.com/photo-1548625149-720754953e6e?w=800&q=80", alt: "Sts. Peter and Paul Parish Church", category: "culture", width: 800, height: 1000 },
  { id: "7", src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80", alt: "Omagieca Mangrove Garden", category: "nature", width: 1200, height: 800 },
  { id: "8", src: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80", alt: "Island Hopping Adventure", category: "activities", width: 1000, height: 800 },
  { id: "9", src: "https://images.unsplash.com/photo-1504870712357-65ea720d6078?w=800&q=80", alt: "Ogtong Cave Resort", category: "nature", width: 1200, height: 800 },
  { id: "10", src: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80", alt: "Sugar Beach Sunrise", category: "beaches", width: 800, height: 1000 },
  { id: "11", src: "https://images.unsplash.com/photo-1536697246787-1f7ae568d89a?w=800&q=80", alt: "Camp Sawi Bonfire Night", category: "activities", width: 1000, height: 800 },
  { id: "12", src: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80", alt: "Mangrove Eco Park Walkway", category: "nature", width: 800, height: 1000 },
  { id: "13", src: "https://images.unsplash.com/photo-1490394813925-88e0b9f10e4e?w=800&q=80", alt: "Silion Island Sandbar", category: "islands", width: 1200, height: 800 },
  { id: "14", src: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80", alt: "Fresh Grilled Seafood Feast", category: "food", width: 1000, height: 800 },
  { id: "15", src: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80", alt: "Bantayan Island Scallops", category: "food", width: 800, height: 1000 },
  { id: "16", src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", alt: "Santa Fe Port Sunrise", category: "culture", width: 1200, height: 800 },
];

export const navItems = [
  { label: "Home", href: "/" },
  { label: "Destinations", href: "/destinations" },
  { label: "Beaches", href: "/beaches" },
  { label: "Attractions", href: "/attractions" },
  { label: "Activities", href: "/activities" },
  { label: "Food", href: "/food" },
  { label: "Hotels", href: "/hotels" },
  { label: "Transportation", href: "/transportation" },
  { label: "Travel Tips", href: "/travel-tips" },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
